services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regression
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - NEW_EMAIL=${NEW_EMAIL}
      - NEW_FIRST_NAME=${NEW_FIRST_NAME}
      - NEW_LAST_NAME=${NEW_LAST_NAME}
      - NEW_GENDER=${NEW_GENDER}